// AUTO-GENERATED by scripts/import-questions.ts — do not edit by hand.
// Run `npm run questions:import` to regenerate from question-bank/ Markdown.
import type { QuestionBank } from "@/lib/types";

export const importedBanks: QuestionBank[] = [
  {
    "id": "sample-bank",
    "name": "Sample Bank",
    "questions": [
      {
        "id": "sample-math-001",
        "module": "math",
        "bankId": "sample-bank",
        "topic": "Algebra",
        "subtopic": "Linear equations",
        "difficulty": "easy",
        "stem": "What is the value of $x$ if $2x + 3 = 11$?",
        "choices": [
          {
            "id": "a",
            "text": "3"
          },
          {
            "id": "b",
            "text": "4"
          },
          {
            "id": "c",
            "text": "5"
          },
          {
            "id": "d",
            "text": "6"
          }
        ],
        "answer": "b",
        "explanation": "Subtract 3 from both sides to get $2x = 8$, then divide by 2 to get $x = 4$.",
        "estimatedTimeSeconds": 60,
        "sourceType": "original_generated",
        "reviewStatus": "needs_review",
        "tags": [
          "equations",
          "solving"
        ]
      },
      {
        "id": "sample-reading-001",
        "module": "reading",
        "bankId": "sample-bank",
        "topic": "Main Idea",
        "difficulty": "medium",
        "stem": "Which statement best expresses the main idea of the passage?",
        "passageId": "sample-psg-coral",
        "choices": [
          {
            "id": "a",
            "text": "Dynamite fishing is the fastest way to fill a net."
          },
          {
            "id": "b",
            "text": "Coral grows too slowly to be worth restoring."
          },
          {
            "id": "c",
            "text": "Restoring the reef ultimately gave the fishers a better livelihood."
          },
          {
            "id": "d",
            "text": "Tourists prefer islands with calm, quiet waters."
          }
        ],
        "answer": "c",
        "explanation": "The passage contrasts the short-term gains of dynamite fishing with the lasting benefits of\nrebuilding the reef, ending on the fishers earning more from the restored reef — choice C.",
        "estimatedTimeSeconds": 60,
        "sourceType": "original_generated",
        "reviewStatus": "needs_review"
      },
      {
        "id": "sample-reading-002",
        "module": "reading",
        "bankId": "sample-bank",
        "topic": "Inference",
        "difficulty": "hard",
        "stem": "What can be inferred about why the catches \"shrank to almost nothing\"?",
        "passageId": "sample-psg-coral",
        "choices": [
          {
            "id": "a",
            "text": "Destroying the coral removed the habitat the fish needed."
          },
          {
            "id": "b",
            "text": "The fishers stopped going out to sea."
          },
          {
            "id": "c",
            "text": "Visitors scared the fish away."
          },
          {
            "id": "d",
            "text": "The island's population grew too quickly."
          }
        ],
        "answer": "a",
        "explanation": "The passage states the fish depended on the coral and that the reef \"went quiet\" after the blasts,\nimplying the loss of habitat caused the decline — choice A.",
        "estimatedTimeSeconds": 75,
        "sourceType": "original_generated",
        "reviewStatus": "needs_review"
      }
    ],
    "passages": [
      {
        "id": "sample-psg-coral",
        "title": "The Coral Gardeners",
        "body": "Off the coast of a small island, fishers once used dynamite to stun fish for a quick catch. The\nblasts filled their nets in minutes, but they also shattered the coral that the fish depended on.\nWithin a few seasons the reef went quiet, and the catches shrank to almost nothing. A handful of the\nfishers decided to try the opposite approach: they fastened broken coral fragments to simple frames\nand lowered them back to the seabed. The work was slow and paid nothing at first. But coral grows,\nand so did the fish that returned to live among it. A decade later the same families were earning\nmore from guiding visitors to the living reef than they had ever earned from destroying it."
      }
    ],
    "description": "Example bank showing the Markdown import format. Not served in the exam."
  }
];
