import type { Question } from "@/lib/types";

/**
 * Language Proficiency — 20 original practice items.
 * Topics: Grammar, Vocabulary, Idioms & Expressions, Sentence Correction, Analogies.
 * All items are original (sourceType: "original_generated"). Do not copy real exam items.
 */
export const languageQuestions: Question[] = [
  {
    id: "lang-001",
    module: "language",
    topic: "Grammar",
    subtopic: "Subject-verb agreement",
    difficulty: "easy",
    stem: "Choose the correct verb: \"Each of the scholars ____ a separate dorm room.\"",
    choices: [
      { id: "a", text: "have" },
      { id: "b", text: "has" },
      { id: "c", text: "having" },
      { id: "d", text: "are having" },
    ],
    answer: "b",
    explanation:
      "\"Each\" is singular, so it takes the singular verb \"has,\" regardless of the plural noun in the prepositional phrase \"of the scholars.\"",
    estimatedTimeSeconds: 35,
    sourceType: "original_generated",
    reviewStatus: "approved",
    tags: ["agreement"],
  },
  {
    id: "lang-002",
    module: "language",
    topic: "Grammar",
    subtopic: "Pronoun case",
    difficulty: "medium",
    stem: "Select the correct option: \"The award was shared between Marisol and ____.\"",
    choices: [
      { id: "a", text: "I" },
      { id: "b", text: "myself" },
      { id: "c", text: "me" },
      { id: "d", text: "mine" },
    ],
    answer: "c",
    explanation:
      "After the preposition \"between,\" use the objective pronoun \"me.\" \"I\" is subjective and \"myself\" is reflexive, neither of which fits here.",
    estimatedTimeSeconds: 35,
    sourceType: "original_generated",
    reviewStatus: "approved",
    tags: ["pronoun"],
  },
  {
    id: "lang-003",
    module: "language",
    topic: "Grammar",
    subtopic: "Verb tense",
    difficulty: "medium",
    stem: "Choose the best completion: \"By the time the results came out, she ____ for three colleges already.\"",
    choices: [
      { id: "a", text: "applied" },
      { id: "b", text: "has applied" },
      { id: "c", text: "had applied" },
      { id: "d", text: "was applying" },
    ],
    answer: "c",
    explanation:
      "The past perfect \"had applied\" shows an action completed before another past event (\"came out\").",
    estimatedTimeSeconds: 40,
    sourceType: "original_generated",
    reviewStatus: "approved",
    tags: ["tense"],
  },
  {
    id: "lang-004",
    module: "language",
    topic: "Grammar",
    subtopic: "Modifiers",
    difficulty: "hard",
    stem: "Which sentence is free of a misplaced modifier?",
    choices: [
      { id: "a", text: "Running to class, the bell rang before Lito arrived." },
      { id: "b", text: "Running to class, Lito heard the bell ring before he arrived." },
      { id: "c", text: "The bell rang running to class before Lito." },
      { id: "d", text: "Before he arrived, the bell running to class rang." },
    ],
    answer: "b",
    explanation:
      "The opening phrase \"Running to class\" must modify the person doing the running. Only option B places \"Lito\" right after the phrase.",
    estimatedTimeSeconds: 45,
    sourceType: "original_generated",
    reviewStatus: "approved",
    tags: ["modifier"],
  },
  {
    id: "lang-005",
    module: "language",
    topic: "Grammar",
    subtopic: "Parallelism",
    difficulty: "medium",
    stem: "Choose the option that keeps the sentence parallel: \"The reviewer told us to read actively, to take notes, and ____.\"",
    choices: [
      { id: "a", text: "you should rest well" },
      { id: "b", text: "resting well" },
      { id: "c", text: "to rest well" },
      { id: "d", text: "that we rest well" },
    ],
    answer: "c",
    explanation:
      "The series uses \"to read\" and \"to take,\" so the third item must also be an infinitive: \"to rest well.\"",
    estimatedTimeSeconds: 40,
    sourceType: "original_generated",
    reviewStatus: "approved",
    tags: ["parallelism"],
  },
  {
    id: "lang-006",
    module: "language",
    topic: "Vocabulary",
    subtopic: "Synonyms",
    difficulty: "easy",
    stem: "Which word is closest in meaning to \"diligent\"?",
    choices: [
      { id: "a", text: "careless" },
      { id: "b", text: "hardworking" },
      { id: "c", text: "cheerful" },
      { id: "d", text: "talented" },
    ],
    answer: "b",
    explanation:
      "\"Diligent\" means showing steady, careful effort, which matches \"hardworking.\"",
    estimatedTimeSeconds: 25,
    sourceType: "original_generated",
    reviewStatus: "approved",
    tags: ["synonym"],
  },
  {
    id: "lang-007",
    module: "language",
    topic: "Vocabulary",
    subtopic: "Antonyms",
    difficulty: "medium",
    stem: "Which word is most nearly opposite in meaning to \"scarce\"?",
    choices: [
      { id: "a", text: "rare" },
      { id: "b", text: "limited" },
      { id: "c", text: "abundant" },
      { id: "d", text: "hidden" },
    ],
    answer: "c",
    explanation:
      "\"Scarce\" means in short supply; its opposite is \"abundant,\" meaning plentiful.",
    estimatedTimeSeconds: 25,
    sourceType: "original_generated",
    reviewStatus: "approved",
    tags: ["antonym"],
  },
  {
    id: "lang-008",
    module: "language",
    topic: "Vocabulary",
    subtopic: "Context clues",
    difficulty: "medium",
    stem: "In \"The lecture was so verbose that students lost track of the main point,\" the word \"verbose\" most likely means:",
    choices: [
      { id: "a", text: "using too many words" },
      { id: "b", text: "very short" },
      { id: "c", text: "carefully organized" },
      { id: "d", text: "loud and angry" },
    ],
    answer: "a",
    explanation:
      "Because students \"lost track of the main point,\" the lecture used excessive words: \"verbose\" means wordy.",
    estimatedTimeSeconds: 40,
    sourceType: "original_generated",
    reviewStatus: "approved",
    tags: ["context"],
  },
  {
    id: "lang-009",
    module: "language",
    topic: "Vocabulary",
    subtopic: "Word usage",
    difficulty: "hard",
    stem: "Choose the word that best completes the sentence: \"Her ____ remarks calmed the worried freshmen.\"",
    choices: [
      { id: "a", text: "abrasive" },
      { id: "b", text: "reassuring" },
      { id: "c", text: "indifferent" },
      { id: "d", text: "ambiguous" },
    ],
    answer: "b",
    explanation:
      "Something that \"calmed\" worried students would be \"reassuring.\" The other choices suggest harshness, coldness, or unclear meaning.",
    estimatedTimeSeconds: 35,
    sourceType: "original_generated",
    reviewStatus: "approved",
    tags: ["usage"],
  },
  {
    id: "lang-010",
    module: "language",
    topic: "Idioms & Expressions",
    subtopic: "Common idioms",
    difficulty: "easy",
    stem: "What does the idiom \"hit the books\" mean?",
    choices: [
      { id: "a", text: "to damage library property" },
      { id: "b", text: "to begin studying seriously" },
      { id: "c", text: "to give up on a subject" },
      { id: "d", text: "to buy new textbooks" },
    ],
    answer: "b",
    explanation: "\"Hit the books\" is an idiom meaning to start studying hard.",
    estimatedTimeSeconds: 25,
    sourceType: "original_generated",
    reviewStatus: "approved",
    tags: ["idiom"],
  },
  {
    id: "lang-011",
    module: "language",
    topic: "Idioms & Expressions",
    subtopic: "Common idioms",
    difficulty: "medium",
    stem: "If a problem is \"a piece of cake,\" it is:",
    choices: [
      { id: "a", text: "very difficult" },
      { id: "b", text: "very easy" },
      { id: "c", text: "expensive" },
      { id: "d", text: "unfair" },
    ],
    answer: "b",
    explanation: "\"A piece of cake\" means something that is very easy to do.",
    estimatedTimeSeconds: 25,
    sourceType: "original_generated",
    reviewStatus: "approved",
    tags: ["idiom"],
  },
  {
    id: "lang-012",
    module: "language",
    topic: "Idioms & Expressions",
    subtopic: "Figurative meaning",
    difficulty: "hard",
    stem: "\"After the long review, the team decided to call it a day.\" This means they:",
    choices: [
      { id: "a", text: "named the day after themselves" },
      { id: "b", text: "stopped working for the day" },
      { id: "c", text: "started a new project" },
      { id: "d", text: "celebrated a holiday" },
    ],
    answer: "b",
    explanation: "\"Call it a day\" means to stop an activity for the day.",
    estimatedTimeSeconds: 30,
    sourceType: "original_generated",
    reviewStatus: "approved",
    tags: ["idiom"],
  },
  {
    id: "lang-013",
    module: "language",
    topic: "Sentence Correction",
    subtopic: "Run-on sentences",
    difficulty: "medium",
    stem: "Which is the best correction for the run-on: \"I finished the exam I felt relieved\"?",
    choices: [
      { id: "a", text: "I finished the exam, I felt relieved." },
      { id: "b", text: "I finished the exam I, felt relieved." },
      { id: "c", text: "After I finished the exam, I felt relieved." },
      { id: "d", text: "I finished the exam felt relieved." },
    ],
    answer: "c",
    explanation:
      "Joining two independent clauses with only a comma (option A) is a comma splice. Option C uses a subordinating conjunction to fix the run-on correctly.",
    estimatedTimeSeconds: 40,
    sourceType: "original_generated",
    reviewStatus: "approved",
    tags: ["run-on"],
  },
  {
    id: "lang-014",
    module: "language",
    topic: "Sentence Correction",
    subtopic: "Redundancy",
    difficulty: "medium",
    stem: "Choose the most concise version: ",
    choices: [
      { id: "a", text: "At this point in time, we are currently reviewing." },
      { id: "b", text: "We are reviewing now." },
      { id: "c", text: "Currently at this time, we review now." },
      { id: "d", text: "Now, at present, we are in the act of reviewing." },
    ],
    answer: "b",
    explanation:
      "Good writing avoids redundancy. \"We are reviewing now\" expresses the idea without repeating the same time reference.",
    estimatedTimeSeconds: 35,
    sourceType: "original_generated",
    reviewStatus: "approved",
    tags: ["concision"],
  },
  {
    id: "lang-015",
    module: "language",
    topic: "Sentence Correction",
    subtopic: "Punctuation",
    difficulty: "hard",
    stem: "Which sentence uses the apostrophe correctly?",
    choices: [
      { id: "a", text: "The students' answers were graded fairly." },
      { id: "b", text: "The student's answers, of all forty of them, agreed." },
      { id: "c", text: "Its' a long review season." },
      { id: "d", text: "The reviewer graded the test's of everyone." },
    ],
    answer: "a",
    explanation:
      "\"Students'\" correctly shows plural possession (answers belonging to many students). The others misuse the apostrophe.",
    estimatedTimeSeconds: 45,
    sourceType: "original_generated",
    reviewStatus: "approved",
    tags: ["punctuation"],
  },
  {
    id: "lang-016",
    module: "language",
    topic: "Analogies",
    subtopic: "Function",
    difficulty: "medium",
    stem: "PEN is to WRITE as SCISSORS is to:",
    choices: [
      { id: "a", text: "paper" },
      { id: "b", text: "sharp" },
      { id: "c", text: "cut" },
      { id: "d", text: "metal" },
    ],
    answer: "c",
    explanation:
      "A pen is a tool used to write; scissors are a tool used to cut. The relationship is tool-to-function.",
    estimatedTimeSeconds: 30,
    sourceType: "original_generated",
    reviewStatus: "approved",
    tags: ["analogy"],
  },
  {
    id: "lang-017",
    module: "language",
    topic: "Analogies",
    subtopic: "Degree",
    difficulty: "hard",
    stem: "WARM is to HOT as DAMP is to:",
    choices: [
      { id: "a", text: "dry" },
      { id: "b", text: "cold" },
      { id: "c", text: "soaked" },
      { id: "d", text: "cool" },
    ],
    answer: "c",
    explanation:
      "\"Warm\" is a lesser degree of \"hot.\" Likewise, \"damp\" is a lesser degree of \"soaked.\" The relationship is degree of intensity.",
    estimatedTimeSeconds: 40,
    sourceType: "original_generated",
    reviewStatus: "approved",
    tags: ["analogy"],
  },
  {
    id: "lang-018",
    module: "language",
    topic: "Analogies",
    subtopic: "Part to whole",
    difficulty: "medium",
    stem: "PETAL is to FLOWER as KEY is to:",
    choices: [
      { id: "a", text: "lock" },
      { id: "b", text: "keyboard" },
      { id: "c", text: "door" },
      { id: "d", text: "metal" },
    ],
    answer: "b",
    explanation:
      "A petal is one part of a flower; a key is one part of a keyboard. The relationship is part-to-whole.",
    estimatedTimeSeconds: 35,
    sourceType: "original_generated",
    reviewStatus: "approved",
    tags: ["analogy"],
  },
  {
    id: "lang-019",
    module: "language",
    topic: "Grammar",
    subtopic: "Articles",
    difficulty: "easy",
    stem: "Choose the correct article: \"She wants to be ____ engineer someday.\"",
    choices: [
      { id: "a", text: "a" },
      { id: "b", text: "an" },
      { id: "c", text: "the" },
      { id: "d", text: "no article" },
    ],
    answer: "b",
    explanation:
      "\"Engineer\" begins with a vowel sound, so it takes \"an.\"",
    estimatedTimeSeconds: 25,
    sourceType: "original_generated",
    reviewStatus: "approved",
    tags: ["article"],
  },
  {
    id: "lang-020",
    module: "language",
    topic: "Vocabulary",
    subtopic: "Prefixes & roots",
    difficulty: "hard",
    stem: "The prefix \"bene-\" in \"benevolent\" suggests a meaning related to:",
    choices: [
      { id: "a", text: "good or well" },
      { id: "b", text: "against" },
      { id: "c", text: "before" },
      { id: "d", text: "around" },
    ],
    answer: "a",
    explanation:
      "The Latin root \"bene-\" means \"good\" or \"well\" (as in benefit, benefactor). \"Benevolent\" means well-meaning or kind.",
    estimatedTimeSeconds: 35,
    sourceType: "original_generated",
    reviewStatus: "approved",
    tags: ["roots"],
  },
];
