import type { Question } from "@/lib/types";

/**
 * Mathematics — 12 original practice items.
 * Topics: Number Sense, Algebra, Geometry, Word Problems, Data Interpretation.
 */
export const mathQuestions: Question[] = [
  {
    id: "math-001",
    module: "math",
    topic: "Number Sense",
    subtopic: "Fractions",
    difficulty: "easy",
    stem: "What is 3/4 + 1/8?",
    choices: [
      { id: "a", text: "4/12" },
      { id: "b", text: "7/8" },
      { id: "c", text: "1/2" },
      { id: "d", text: "5/8" },
    ],
    answer: "b",
    explanation: "Convert to eighths: 3/4 = 6/8. Then 6/8 + 1/8 = 7/8.",
    estimatedTimeSeconds: 45,
    sourceType: "original_generated",
    reviewStatus: "approved",
    tags: ["fractions"],
  },
  {
    id: "math-002",
    module: "math",
    topic: "Number Sense",
    subtopic: "Percentage",
    difficulty: "easy",
    stem: "A reviewer costs ₱800. With a 15% discount, how much do you pay?",
    choices: [
      { id: "a", text: "₱680" },
      { id: "b", text: "₱720" },
      { id: "c", text: "₱785" },
      { id: "d", text: "₱120" },
    ],
    answer: "a",
    explanation: "15% of 800 is 120. The price paid is 800 − 120 = ₱680.",
    estimatedTimeSeconds: 45,
    sourceType: "original_generated",
    reviewStatus: "approved",
    tags: ["percentage"],
  },
  {
    id: "math-003",
    module: "math",
    topic: "Algebra",
    subtopic: "Linear equations",
    difficulty: "medium",
    stem: "Solve for x: 3x − 7 = 11.",
    choices: [
      { id: "a", text: "x = 6" },
      { id: "b", text: "x = 4" },
      { id: "c", text: "x = 18" },
      { id: "d", text: "x = 3" },
    ],
    answer: "a",
    explanation: "Add 7 to both sides: 3x = 18. Divide by 3: x = 6.",
    estimatedTimeSeconds: 40,
    sourceType: "original_generated",
    reviewStatus: "approved",
    tags: ["linear"],
  },
  {
    id: "math-004",
    module: "math",
    topic: "Algebra",
    subtopic: "Systems",
    difficulty: "hard",
    stem: "If x + y = 10 and x − y = 4, what is x?",
    choices: [
      { id: "a", text: "3" },
      { id: "b", text: "5" },
      { id: "c", text: "7" },
      { id: "d", text: "6" },
    ],
    answer: "c",
    explanation:
      "Add the two equations: (x + y) + (x − y) = 10 + 4, so 2x = 14 and x = 7.",
    estimatedTimeSeconds: 55,
    sourceType: "original_generated",
    reviewStatus: "approved",
    tags: ["systems"],
  },
  {
    id: "math-005",
    module: "math",
    topic: "Algebra",
    subtopic: "Exponents",
    difficulty: "medium",
    stem: "Simplify: 2³ × 2².",
    choices: [
      { id: "a", text: "2⁵ = 32" },
      { id: "b", text: "2⁶ = 64" },
      { id: "c", text: "4⁵ = 1024" },
      { id: "d", text: "2¹ = 2" },
    ],
    answer: "a",
    explanation:
      "When multiplying like bases, add exponents: 2³ × 2² = 2^(3+2) = 2⁵ = 32.",
    estimatedTimeSeconds: 40,
    sourceType: "original_generated",
    reviewStatus: "approved",
    tags: ["exponents"],
  },
  {
    id: "math-006",
    module: "math",
    topic: "Geometry",
    subtopic: "Area",
    difficulty: "easy",
    stem: "What is the area of a rectangle that is 8 cm long and 5 cm wide?",
    image: {
      src: "/questions/core/math-006.svg",
      alt: "A rectangle labeled 8 cm by 5 cm.",
      caption: "Rectangle dimensions",
    },
    choices: [
      { id: "a", text: "13 cm²" },
      { id: "b", text: "26 cm²" },
      { id: "c", text: "40 cm²" },
      { id: "d", text: "45 cm²" },
    ],
    answer: "c",
    explanation: "Area of a rectangle = length × width = 8 × 5 = 40 cm².",
    estimatedTimeSeconds: 35,
    sourceType: "original_generated",
    reviewStatus: "approved",
    tags: ["area"],
  },
  {
    id: "math-007",
    module: "math",
    topic: "Geometry",
    subtopic: "Triangles",
    difficulty: "medium",
    stem: "Two angles of a triangle measure 50° and 65°. What is the third angle?",
    image: {
      src: "/questions/core/math-007.svg",
      alt: "A triangle with two angles labeled 50 degrees and 65 degrees and the third angle unknown.",
      caption: "Triangle angle sum",
    },
    choices: [
      { id: "a", text: "55°" },
      { id: "b", text: "65°" },
      { id: "c", text: "75°" },
      { id: "d", text: "115°" },
    ],
    answer: "b",
    explanation:
      "Angles of a triangle sum to 180°. So the third angle = 180 − (50 + 65) = 180 − 115 = 65°.",
    estimatedTimeSeconds: 45,
    sourceType: "original_generated",
    reviewStatus: "approved",
    tags: ["triangles"],
  },
  {
    id: "math-008",
    module: "math",
    topic: "Geometry",
    subtopic: "Pythagorean theorem",
    difficulty: "hard",
    stem: "A right triangle has legs of 6 and 8. What is the length of the hypotenuse?",
    image: {
      src: "/questions/core/math-008.svg",
      alt: "A right triangle with legs 6 and 8 and hypotenuse unknown.",
      caption: "Right triangle",
    },
    choices: [
      { id: "a", text: "10" },
      { id: "b", text: "12" },
      { id: "c", text: "14" },
      { id: "d", text: "48" },
    ],
    answer: "a",
    explanation:
      "By the Pythagorean theorem, hypotenuse = √(6² + 8²) = √(36 + 64) = √100 = 10.",
    estimatedTimeSeconds: 55,
    sourceType: "original_generated",
    reviewStatus: "approved",
    tags: ["pythagorean"],
  },
  {
    id: "math-009",
    module: "math",
    topic: "Word Problems",
    subtopic: "Rate",
    difficulty: "medium",
    stem: "A jeepney travels 60 km in 1.5 hours at a steady speed. What is its average speed?",
    choices: [
      { id: "a", text: "30 km/h" },
      { id: "b", text: "40 km/h" },
      { id: "c", text: "45 km/h" },
      { id: "d", text: "90 km/h" },
    ],
    answer: "b",
    explanation: "Average speed = distance ÷ time = 60 ÷ 1.5 = 40 km/h.",
    estimatedTimeSeconds: 50,
    sourceType: "original_generated",
    reviewStatus: "approved",
    tags: ["rate"],
  },
  {
    id: "math-010",
    module: "math",
    topic: "Word Problems",
    subtopic: "Ratio",
    difficulty: "hard",
    stem: "Sand and cement are mixed in a ratio of 3:1. If you use 12 kg of sand, how much cement is needed?",
    image: {
      src: "/questions/core/math-010.svg",
      alt: "A ratio bar showing 3 parts sand and 1 part cement.",
      caption: "Sand to cement ratio",
    },
    choices: [
      { id: "a", text: "3 kg" },
      { id: "b", text: "4 kg" },
      { id: "c", text: "6 kg" },
      { id: "d", text: "36 kg" },
    ],
    answer: "b",
    explanation:
      "The ratio 3:1 means cement = sand ÷ 3 = 12 ÷ 3 = 4 kg.",
    estimatedTimeSeconds: 55,
    sourceType: "original_generated",
    reviewStatus: "approved",
    tags: ["ratio"],
  },
  {
    id: "math-011",
    module: "math",
    topic: "Data Interpretation",
    subtopic: "Average",
    difficulty: "medium",
    stem: "A student's four quiz scores are 12, 15, 18, and 15. What is the mean score?",
    choices: [
      { id: "a", text: "14" },
      { id: "b", text: "15" },
      { id: "c", text: "16" },
      { id: "d", text: "60" },
    ],
    answer: "b",
    explanation:
      "Mean = (12 + 15 + 18 + 15) ÷ 4 = 60 ÷ 4 = 15.",
    estimatedTimeSeconds: 45,
    sourceType: "original_generated",
    reviewStatus: "approved",
    tags: ["average"],
  },
  {
    id: "math-012",
    module: "math",
    topic: "Data Interpretation",
    subtopic: "Probability",
    difficulty: "hard",
    stem: "A bag has 3 red and 5 blue marbles. What is the probability of drawing a red marble at random?",
    image: {
      src: "/questions/core/math-012.svg",
      alt: "A bag containing 3 red marbles and 5 blue marbles.",
      caption: "Marbles in the bag",
    },
    choices: [
      { id: "a", text: "3/5" },
      { id: "b", text: "3/8" },
      { id: "c", text: "5/8" },
      { id: "d", text: "1/3" },
    ],
    answer: "b",
    explanation:
      "Probability = favorable ÷ total = 3 red ÷ (3 + 5) total = 3/8.",
    estimatedTimeSeconds: 50,
    sourceType: "original_generated",
    reviewStatus: "approved",
    tags: ["probability"],
  },
];
