import type { Question } from "@/lib/types";

/**
 * Reading Comprehension — 16 original practice items across 4 original passages.
 * Topics: Main Idea, Inference, Vocabulary in Context, Author's Purpose, Detail.
 */
export const readingQuestions: Question[] = [
  // --- Passage: The Tricycle Cooperative ---
  {
    id: "read-001",
    module: "reading",
    topic: "Main Idea",
    difficulty: "medium",
    passageId: "psg-tricycle",
    stem: "Which statement best expresses the main idea of the passage?",
    choices: [
      { id: "a", text: "Tricycle drivers in San Vicente earn more than other workers." },
      { id: "b", text: "Cooperation among drivers reduced waste and raised earnings." },
      { id: "c", text: "There are too many tricycles in Philippine towns." },
      { id: "d", text: "The cooperative made all the drivers wealthy." },
    ],
    answer: "b",
    explanation:
      "The passage shows that organizing into a cooperative cut wasted fuel and time, which raised earnings. It explicitly says no one became rich, so D is wrong.",
    estimatedTimeSeconds: 50,
    sourceType: "original_generated",
    reviewStatus: "approved",
    tags: ["main-idea"],
  },
  {
    id: "read-002",
    module: "reading",
    topic: "Detail",
    difficulty: "easy",
    passageId: "psg-tricycle",
    stem: "According to the passage, why did earnings rise after the cooperative formed?",
    choices: [
      { id: "a", text: "There were many more passengers." },
      { id: "b", text: "Fares were raised sharply." },
      { id: "c", text: "Drivers stopped wasting fuel and time competing." },
      { id: "d", text: "The town gave the drivers money." },
    ],
    answer: "c",
    explanation:
      "The passage states earnings rose \"not because there were more passengers\" but because drivers stopped wasting fuel and time fighting over them.",
    estimatedTimeSeconds: 40,
    sourceType: "original_generated",
    reviewStatus: "approved",
    tags: ["detail"],
  },
  {
    id: "read-003",
    module: "reading",
    topic: "Author's Purpose",
    difficulty: "hard",
    passageId: "psg-tricycle",
    stem: "The final sentence, \"It simply turned a scramble into a system,\" mainly serves to:",
    choices: [
      { id: "a", text: "summarize the value of organizing a shared process" },
      { id: "b", text: "criticize the drivers for being disorganized" },
      { id: "c", text: "argue that cooperatives always fail" },
      { id: "d", text: "describe the town's geography" },
    ],
    answer: "a",
    explanation:
      "The closing line restates the central point: order replaced chaos. It frames the benefit, not a criticism or unrelated detail.",
    estimatedTimeSeconds: 50,
    sourceType: "original_generated",
    reviewStatus: "approved",
    tags: ["purpose"],
  },
  {
    id: "read-004",
    module: "reading",
    topic: "Vocabulary in Context",
    difficulty: "medium",
    passageId: "psg-tricycle",
    stem: "In the passage, the word \"idling\" most nearly means:",
    choices: [
      { id: "a", text: "speeding recklessly" },
      { id: "b", text: "waiting without working" },
      { id: "c", text: "repairing engines" },
      { id: "d", text: "earning extra money" },
    ],
    answer: "b",
    explanation:
      "Drivers were \"idling for hours with empty seats,\" meaning they were waiting idly without earning, so \"waiting without working\" fits.",
    estimatedTimeSeconds: 40,
    sourceType: "original_generated",
    reviewStatus: "approved",
    tags: ["vocab-context"],
  },

  // --- Passage: Why Fireflies Are Fading ---
  {
    id: "read-005",
    module: "reading",
    topic: "Inference",
    difficulty: "hard",
    passageId: "psg-firefly",
    stem: "It can be inferred from the passage that fireflies decline near resorts mainly because:",
    choices: [
      { id: "a", text: "the insects are being poisoned by chemicals" },
      { id: "b", text: "their food supply has disappeared" },
      { id: "c", text: "artificial light disrupts their mating signals" },
      { id: "d", text: "tourists collect them as souvenirs" },
    ],
    answer: "c",
    explanation:
      "The passage says the insects are not poisoned and their food has not vanished; they simply cannot find one another because light drowns out their signals.",
    estimatedTimeSeconds: 50,
    sourceType: "original_generated",
    reviewStatus: "approved",
    tags: ["inference"],
  },
  {
    id: "read-006",
    module: "reading",
    topic: "Vocabulary in Context",
    difficulty: "medium",
    passageId: "psg-firefly",
    stem: "The comparison \"much as a whisper is lost in a noisy room\" is used to explain how:",
    choices: [
      { id: "a", text: "fireflies make sound to attract mates" },
      { id: "b", text: "bright light overwhelms the fireflies' light signals" },
      { id: "c", text: "rooms become too crowded at night" },
      { id: "d", text: "fireflies prefer to live indoors" },
    ],
    answer: "b",
    explanation:
      "The simile compares a faint whisper lost in noise to faint flashes lost in bright light, clarifying how lamps overwhelm firefly signals.",
    estimatedTimeSeconds: 45,
    sourceType: "original_generated",
    reviewStatus: "approved",
    tags: ["vocab-context"],
  },
  {
    id: "read-007",
    module: "reading",
    topic: "Main Idea",
    difficulty: "medium",
    passageId: "psg-firefly",
    stem: "Which title best captures the passage's central concern?",
    choices: [
      { id: "a", text: "How Fireflies Make Light" },
      { id: "b", text: "The Danger of River Pollution" },
      { id: "c", text: "How Artificial Light Threatens Fireflies" },
      { id: "d", text: "Building Resorts by the River" },
    ],
    answer: "c",
    explanation:
      "The passage centers on how all-night artificial light prevents fireflies from communicating and reduces their numbers.",
    estimatedTimeSeconds: 45,
    sourceType: "original_generated",
    reviewStatus: "approved",
    tags: ["main-idea"],
  },
  {
    id: "read-008",
    module: "reading",
    topic: "Detail",
    difficulty: "easy",
    passageId: "psg-firefly",
    stem: "What did some communities do in response to the problem?",
    choices: [
      { id: "a", text: "They added more lamps along the river." },
      { id: "b", text: "They dimmed shoreline lights for a few weeks each year." },
      { id: "c", text: "They moved the fireflies to new streams." },
      { id: "d", text: "They banned all tourism permanently." },
    ],
    answer: "b",
    explanation:
      "The passage states that some communities dimmed shoreline lights for a few weeks each year, and the glow slowly returned.",
    estimatedTimeSeconds: 40,
    sourceType: "original_generated",
    reviewStatus: "approved",
    tags: ["detail"],
  },

  // --- Passage: The Terraces and the Tourists ---
  {
    id: "read-009",
    module: "reading",
    topic: "Author's Purpose",
    difficulty: "hard",
    passageId: "psg-rice",
    stem: "The author most likely wrote this passage to:",
    choices: [
      { id: "a", text: "encourage more tourists to photograph the terraces" },
      { id: "b", text: "warn that valuing only the view may endanger the terraces" },
      { id: "c", text: "explain how rice is cooked in the mountains" },
      { id: "d", text: "argue that the terraces should be abandoned" },
    ],
    answer: "b",
    explanation:
      "The passage repeatedly contrasts admiring the view with the labor that sustains the terraces, warning that the skill could fade if only the view is valued.",
    estimatedTimeSeconds: 50,
    sourceType: "original_generated",
    reviewStatus: "approved",
    tags: ["purpose"],
  },
  {
    id: "read-010",
    module: "reading",
    topic: "Inference",
    difficulty: "medium",
    passageId: "psg-rice",
    stem: "The passage suggests that training young guides to also farm is meant to:",
    choices: [
      { id: "a", text: "increase ticket prices for tourists" },
      { id: "b", text: "preserve the knowledge needed to maintain the terraces" },
      { id: "c", text: "replace farming with tourism entirely" },
      { id: "d", text: "discourage young people from leaving the city" },
    ],
    answer: "b",
    explanation:
      "Villages bet that the terraces will survive only if those who show them also know how to repair them, preserving maintenance knowledge.",
    estimatedTimeSeconds: 45,
    sourceType: "original_generated",
    reviewStatus: "approved",
    tags: ["inference"],
  },
  {
    id: "read-011",
    module: "reading",
    topic: "Vocabulary in Context",
    difficulty: "medium",
    passageId: "psg-rice",
    stem: "As used in the passage, \"backdrop\" most nearly means:",
    choices: [
      { id: "a", text: "a source of income" },
      { id: "b", text: "a decorative background" },
      { id: "c", text: "a farming tool" },
      { id: "d", text: "a type of rice" },
    ],
    answer: "b",
    explanation:
      "\"Valued only as a backdrop\" means valued only as a background for photos, i.e., decoration rather than working farmland.",
    estimatedTimeSeconds: 40,
    sourceType: "original_generated",
    reviewStatus: "approved",
    tags: ["vocab-context"],
  },
  {
    id: "read-012",
    module: "reading",
    topic: "Detail",
    difficulty: "easy",
    passageId: "psg-rice",
    stem: "According to the passage, why do younger residents increasingly leave?",
    choices: [
      { id: "a", text: "The terraces have already collapsed." },
      { id: "b", text: "Maintaining the walls is hard work that pays little." },
      { id: "c", text: "Tourists have banned them from the fields." },
      { id: "d", text: "The government closed the farms." },
    ],
    answer: "b",
    explanation:
      "The passage states that keeping the walls intact is exhausting work that pays little, so younger residents leave for city jobs.",
    estimatedTimeSeconds: 40,
    sourceType: "original_generated",
    reviewStatus: "approved",
    tags: ["detail"],
  },

  // --- Passage: A Library Without Walls ---
  {
    id: "read-013",
    module: "reading",
    topic: "Main Idea",
    difficulty: "medium",
    passageId: "psg-library",
    stem: "The main point of the passage is that:",
    choices: [
      { id: "a", text: "libraries should never be rebuilt after storms" },
      { id: "b", text: "a library's value lies in reading habits, not its building" },
      { id: "c", text: "motorbikes are the best way to store books" },
      { id: "d", text: "children dislike visiting library buildings" },
    ],
    answer: "b",
    explanation:
      "The closing line states that a library is not a place but a habit, and borrowing rose even without the building.",
    estimatedTimeSeconds: 45,
    sourceType: "original_generated",
    reviewStatus: "approved",
    tags: ["main-idea"],
  },
  {
    id: "read-014",
    module: "reading",
    topic: "Inference",
    difficulty: "hard",
    passageId: "psg-library",
    stem: "It can be inferred that borrowing rose mainly because the librarian:",
    choices: [
      { id: "a", text: "offered books matched to each reader's interests" },
      { id: "b", text: "lowered the price of borrowing books" },
      { id: "c", text: "built a larger library building" },
      { id: "d", text: "required families to read every weekend" },
    ],
    answer: "a",
    explanation:
      "She kept notes on what each reader enjoyed and returned with titles chosen for them by name, which drew more readers despite fewer books.",
    estimatedTimeSeconds: 50,
    sourceType: "original_generated",
    reviewStatus: "approved",
    tags: ["inference"],
  },
  {
    id: "read-015",
    module: "reading",
    topic: "Detail",
    difficulty: "easy",
    passageId: "psg-library",
    stem: "How many books could the crate hold at a time?",
    choices: [
      { id: "a", text: "ten" },
      { id: "b", text: "thirty" },
      { id: "c", text: "three hundred" },
      { id: "d", text: "as many as the shelves" },
    ],
    answer: "b",
    explanation:
      "The passage states the crate could hold only thirty volumes at a time, far fewer than the shelves it replaced.",
    estimatedTimeSeconds: 35,
    sourceType: "original_generated",
    reviewStatus: "approved",
    tags: ["detail"],
  },
  {
    id: "read-016",
    module: "reading",
    topic: "Author's Purpose",
    difficulty: "medium",
    passageId: "psg-library",
    stem: "The detail that parents began requesting books on \"boat repair and weather\" mainly shows that:",
    choices: [
      { id: "a", text: "the service reached new readers with practical needs" },
      { id: "b", text: "the librarian disliked fiction" },
      { id: "c", text: "the building was finally repaired" },
      { id: "d", text: "children stopped borrowing books" },
    ],
    answer: "a",
    explanation:
      "Parents who had never entered the old building began requesting practical titles, showing the mobile service reached new kinds of readers.",
    estimatedTimeSeconds: 45,
    sourceType: "original_generated",
    reviewStatus: "approved",
    tags: ["purpose"],
  },
];
