import type { Question } from "@/lib/types";

/**
 * Science — 15 original practice items.
 * Topics: Biology, Chemistry, Physics, Earth Science, General Science.
 */
export const scienceQuestions: Question[] = [
  {
    id: "sci-001",
    module: "science",
    topic: "Biology",
    subtopic: "Cell biology",
    difficulty: "easy",
    stem: "Which cell structure is mainly responsible for producing energy (ATP)?",
    choices: [
      { id: "a", text: "Nucleus" },
      { id: "b", text: "Ribosome" },
      { id: "c", text: "Mitochondrion" },
      { id: "d", text: "Cell wall" },
    ],
    answer: "c",
    explanation:
      "The mitochondrion is the site of cellular respiration, which produces most of the cell's ATP, often called the cell's powerhouse.",
    estimatedTimeSeconds: 35,
    sourceType: "original_generated",
    reviewStatus: "approved",
    tags: ["cells"],
  },
  {
    id: "sci-002",
    module: "science",
    topic: "Biology",
    subtopic: "Photosynthesis",
    difficulty: "medium",
    stem: "During photosynthesis, plants mainly take in carbon dioxide and release:",
    choices: [
      { id: "a", text: "nitrogen" },
      { id: "b", text: "oxygen" },
      { id: "c", text: "hydrogen" },
      { id: "d", text: "methane" },
    ],
    answer: "b",
    explanation:
      "Photosynthesis uses carbon dioxide and water with light energy to make glucose, releasing oxygen as a by-product.",
    estimatedTimeSeconds: 40,
    sourceType: "original_generated",
    reviewStatus: "approved",
    tags: ["plants"],
  },
  {
    id: "sci-003",
    module: "science",
    topic: "Biology",
    subtopic: "Human body",
    difficulty: "easy",
    stem: "Which organ system is primarily responsible for transporting oxygen and nutrients throughout the body?",
    choices: [
      { id: "a", text: "Digestive system" },
      { id: "b", text: "Circulatory system" },
      { id: "c", text: "Skeletal system" },
      { id: "d", text: "Nervous system" },
    ],
    answer: "b",
    explanation:
      "The circulatory system, driven by the heart, carries oxygen and nutrients to cells and removes wastes via the blood.",
    estimatedTimeSeconds: 35,
    sourceType: "original_generated",
    reviewStatus: "approved",
    tags: ["body-systems"],
  },
  {
    id: "sci-004",
    module: "science",
    topic: "Chemistry",
    subtopic: "Atomic structure",
    difficulty: "medium",
    stem: "Which subatomic particle carries a negative charge?",
    choices: [
      { id: "a", text: "Proton" },
      { id: "b", text: "Neutron" },
      { id: "c", text: "Electron" },
      { id: "d", text: "Nucleus" },
    ],
    answer: "c",
    explanation:
      "Electrons carry a negative charge, protons are positive, and neutrons are neutral.",
    estimatedTimeSeconds: 35,
    sourceType: "original_generated",
    reviewStatus: "approved",
    tags: ["atoms"],
  },
  {
    id: "sci-005",
    module: "science",
    topic: "Chemistry",
    subtopic: "States of matter",
    difficulty: "easy",
    stem: "The process by which a liquid changes into a gas is called:",
    choices: [
      { id: "a", text: "condensation" },
      { id: "b", text: "evaporation" },
      { id: "c", text: "freezing" },
      { id: "d", text: "sublimation" },
    ],
    answer: "b",
    explanation:
      "Evaporation is the change from liquid to gas. Condensation is gas to liquid, and freezing is liquid to solid.",
    estimatedTimeSeconds: 35,
    sourceType: "original_generated",
    reviewStatus: "approved",
    tags: ["matter"],
  },
  {
    id: "sci-006",
    module: "science",
    topic: "Chemistry",
    subtopic: "Acids and bases",
    difficulty: "hard",
    stem: "On the pH scale, a solution with a pH of 3 is best described as:",
    choices: [
      { id: "a", text: "strongly basic" },
      { id: "b", text: "neutral" },
      { id: "c", text: "acidic" },
      { id: "d", text: "salty" },
    ],
    answer: "c",
    explanation:
      "A pH below 7 is acidic, 7 is neutral, and above 7 is basic. A pH of 3 is acidic.",
    estimatedTimeSeconds: 40,
    sourceType: "original_generated",
    reviewStatus: "approved",
    tags: ["ph"],
  },
  {
    id: "sci-007",
    module: "science",
    topic: "Physics",
    subtopic: "Forces and motion",
    difficulty: "medium",
    stem: "Newton's first law of motion is often described as the law of:",
    choices: [
      { id: "a", text: "acceleration" },
      { id: "b", text: "inertia" },
      { id: "c", text: "gravity" },
      { id: "d", text: "friction" },
    ],
    answer: "b",
    explanation:
      "Newton's first law (the law of inertia) states that an object stays at rest or in uniform motion unless acted on by a net external force.",
    estimatedTimeSeconds: 40,
    sourceType: "original_generated",
    reviewStatus: "approved",
    tags: ["motion"],
  },
  {
    id: "sci-008",
    module: "science",
    topic: "Physics",
    subtopic: "Energy",
    difficulty: "medium",
    stem: "A ball held at the top of a hill has energy due to its position. This is called:",
    choices: [
      { id: "a", text: "kinetic energy" },
      { id: "b", text: "thermal energy" },
      { id: "c", text: "potential energy" },
      { id: "d", text: "sound energy" },
    ],
    answer: "c",
    explanation:
      "Energy stored due to position or height is gravitational potential energy. Kinetic energy is energy of motion.",
    estimatedTimeSeconds: 40,
    sourceType: "original_generated",
    reviewStatus: "approved",
    tags: ["energy"],
  },
  {
    id: "sci-009",
    module: "science",
    topic: "Physics",
    subtopic: "Electricity",
    difficulty: "hard",
    stem: "Using Ohm's law, what is the current through a 12-volt circuit with a resistance of 4 ohms?",
    choices: [
      { id: "a", text: "3 amperes" },
      { id: "b", text: "8 amperes" },
      { id: "c", text: "16 amperes" },
      { id: "d", text: "48 amperes" },
    ],
    answer: "a",
    explanation:
      "Ohm's law: current = voltage ÷ resistance = 12 ÷ 4 = 3 amperes.",
    estimatedTimeSeconds: 50,
    sourceType: "original_generated",
    reviewStatus: "approved",
    tags: ["electricity"],
  },
  {
    id: "sci-010",
    module: "science",
    topic: "Earth Science",
    subtopic: "Weather",
    difficulty: "easy",
    stem: "Which instrument is used to measure atmospheric pressure?",
    choices: [
      { id: "a", text: "Thermometer" },
      { id: "b", text: "Barometer" },
      { id: "c", text: "Anemometer" },
      { id: "d", text: "Hygrometer" },
    ],
    answer: "b",
    explanation:
      "A barometer measures atmospheric pressure. A thermometer measures temperature, an anemometer wind speed, and a hygrometer humidity.",
    estimatedTimeSeconds: 35,
    sourceType: "original_generated",
    reviewStatus: "approved",
    tags: ["weather"],
  },
  {
    id: "sci-011",
    module: "science",
    topic: "Earth Science",
    subtopic: "Geology",
    difficulty: "medium",
    stem: "The Philippines experiences frequent earthquakes mainly because it lies along:",
    choices: [
      { id: "a", text: "the equator" },
      { id: "b", text: "a major ocean current" },
      { id: "c", text: "the Pacific Ring of Fire" },
      { id: "d", text: "the prime meridian" },
    ],
    answer: "c",
    explanation:
      "The Philippines sits on the Pacific Ring of Fire, a zone of active tectonic plate boundaries with frequent earthquakes and volcanoes.",
    estimatedTimeSeconds: 40,
    sourceType: "original_generated",
    reviewStatus: "approved",
    tags: ["geology"],
  },
  {
    id: "sci-012",
    module: "science",
    topic: "Earth Science",
    subtopic: "Astronomy",
    difficulty: "medium",
    stem: "What causes day and night on Earth?",
    choices: [
      { id: "a", text: "Earth's revolution around the Sun" },
      { id: "b", text: "Earth's rotation on its axis" },
      { id: "c", text: "The Moon blocking the Sun" },
      { id: "d", text: "Changes in the seasons" },
    ],
    answer: "b",
    explanation:
      "Earth's rotation on its axis (about once every 24 hours) causes day and night. Revolution around the Sun causes the year and seasons.",
    estimatedTimeSeconds: 40,
    sourceType: "original_generated",
    reviewStatus: "approved",
    tags: ["astronomy"],
  },
  {
    id: "sci-013",
    module: "science",
    topic: "Biology",
    subtopic: "Ecology",
    difficulty: "medium",
    stem: "In a food chain, organisms that make their own food using sunlight are called:",
    choices: [
      { id: "a", text: "consumers" },
      { id: "b", text: "decomposers" },
      { id: "c", text: "producers" },
      { id: "d", text: "predators" },
    ],
    answer: "c",
    explanation:
      "Producers (such as green plants) make their own food through photosynthesis and form the base of the food chain.",
    estimatedTimeSeconds: 40,
    sourceType: "original_generated",
    reviewStatus: "approved",
    tags: ["ecology"],
  },
  {
    id: "sci-014",
    module: "science",
    topic: "Chemistry",
    subtopic: "Mixtures",
    difficulty: "hard",
    stem: "Which of the following is a chemical change rather than a physical change?",
    choices: [
      { id: "a", text: "Melting ice into water" },
      { id: "b", text: "Dissolving sugar in water" },
      { id: "c", text: "Rusting of an iron nail" },
      { id: "d", text: "Cutting a sheet of paper" },
    ],
    answer: "c",
    explanation:
      "Rusting forms a new substance (iron oxide), so it is a chemical change. The others change form but not the underlying substance.",
    estimatedTimeSeconds: 45,
    sourceType: "original_generated",
    reviewStatus: "approved",
    tags: ["reactions"],
  },
  {
    id: "sci-015",
    module: "science",
    topic: "General Science",
    subtopic: "Scientific method",
    difficulty: "easy",
    stem: "In an experiment, the factor that the researcher deliberately changes is the:",
    choices: [
      { id: "a", text: "dependent variable" },
      { id: "b", text: "independent variable" },
      { id: "c", text: "control" },
      { id: "d", text: "constant" },
    ],
    answer: "b",
    explanation:
      "The independent variable is the one the researcher changes on purpose; the dependent variable is what is measured in response.",
    estimatedTimeSeconds: 40,
    sourceType: "original_generated",
    reviewStatus: "approved",
    tags: ["method"],
  },
];
